/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yayamamo;

public class IndriPorter {
  public static int Porter_Stemmer_porter_stem(SWIGTYPE_p_Porter_Stemmer self, String p, int i, int j) {
    return IndriPorterJNI.Porter_Stemmer_porter_stem(SWIGTYPE_p_Porter_Stemmer.getCPtr(self), p, i, j);
  }

  public static String Porter_Stemmer_porter_stem_y(SWIGTYPE_p_Porter_Stemmer self, String p, int i, int j) {
    return IndriPorterJNI.Porter_Stemmer_porter_stem_y(SWIGTYPE_p_Porter_Stemmer.getCPtr(self), p, i, j);
  }

  public static SWIGTYPE_p_Porter_Stemmer new_Porter_Stemmer() {
    long cPtr = IndriPorterJNI.new_Porter_Stemmer();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Porter_Stemmer(cPtr, true);
  }

  public static void delete_Porter_Stemmer(SWIGTYPE_p_Porter_Stemmer self) {
    IndriPorterJNI.delete_Porter_Stemmer(SWIGTYPE_p_Porter_Stemmer.getCPtr(self));
  }

}
