/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yayamamo;

class IndriPorterJNI {
  public final static native int Porter_Stemmer_porter_stem(long jarg1, String jarg2, int jarg3, int jarg4);
  public final static native String Porter_Stemmer_porter_stem_y(long jarg1, String jarg2, int jarg3, int jarg4);
  public final static native long new_Porter_Stemmer();
  public final static native void delete_Porter_Stemmer(long jarg1);
}
